In [1]:
import numpy as np 

In [ ]:
ar = np.array([[ 1, 2, 3, 4, 5], 
               [ 5, 4, 3, 2, 1 ], 
               [11, 22, 33, 44, 55]
               ])
ar[1:3, 1:4] 

array([[ 4,  3,  2],
       [22, 33, 44]])

In [22]:
ar.sum(axis=1)  # Sum along the first axis (rows)
# ar.sum(axis=0)  # Sum along the second axis (columns)

array([ 15,  15, 165])

In [30]:
a = np.arange(1, 10, 2)  # Create an array with a step of 2
a + 10  # Add 10 to each element of the array
a * 2  # Multiply each element of the array by 2
a+= 100
a

array([101, 103, 105, 107, 109])

In [ ]:
l = np.array([1, 2, 3, 4, 5])
[i * 10 for i in l]

[10, 20, 30, 40, 50]

In [33]:
l[[True, False, True, False, True]]  # Boolean indexing

array([1, 3, 5])

In [44]:
l[l > 2] # Boolean indexing to get elements greater than 2

array([3, 4, 5])

In [54]:
l[~(l.mean() > 2)]  # Boolean indexing to get elements less than the mean

array([], shape=(0, 5), dtype=int32)

In [ ]:
l = list(range(1, 10))
%timeit sum([i**2 for i in l])  # List comprehension timing

539 ns ± 5.18 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [58]:
a = np.arange(1000)
%timeit np.sum(a**2)  # Numpy array operation timing

3.73 μs ± 39.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [76]:
# np.identity(3)  # Get the identity of the array object
np.eye(3, 3)  # Get the identity of the array object (alternative method)
np.eye(3, 3, k=1)  # Get the identity of the array object with an offset diagonal
np.eye(6, 4, k=-1)  # Get the identity of the array object with an offset diagonal
"Hello World"[6]  # String slicing to get a substring


'W'