In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [7]:
digits = load_digits()

In [15]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [16]:
lr= LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

c:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [17]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [18]:
rf= RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9814814814814815

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf


KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8]):
    print(train_index, test_index)

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [24]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [26]:
get_score(LogisticRegression(), x_train,x_test, y_train,y_test)

c:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [29]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [40]:
scores_lr = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train, X_test , Y_train , Y_test =  digits.data[train_index], digits.data[test_index] , digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression() , X_train ,X_test , Y_train , Y_test))
    scores_svm.append(get_score(SVC() , X_train ,X_test , Y_train , Y_test))
    scores_rf.append(get_score(RandomForestClassifier() , X_train ,X_test , Y_train , Y_test))

c:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [41]:
print("Logistic Scores are:",scores_lr,"\nSVM Scores are:", scores_svm ,"\nRandomForest Scores are:", scores_rf)

Logistic Scores are: [0.9232053422370617, 0.9415692821368948, 0.9148580968280468] 
SVM Scores are: [0.9666110183639399, 0.9816360601001669, 0.9549248747913188] 
RandomForest Scores are: [0.9332220367278798, 0.9449081803005008, 0.9248747913188647]


In [55]:
# Doing the same thing with cross_val_score as above done by using for loop
from sklearn.model_selection import cross_val_score
scores_lr= cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)
scores_svm =cross_val_score(SVC(), digits.data, digits.target, cv=3)  
scores_rf =cross_val_score(RandomForestClassifier(n_estimators=64), digits.data, digits.target, cv=3)

c:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [56]:
print("Logistic Scores",scores_lr,"\nSVM Scores", scores_svm ,"\nRandomForest Scores", scores_rf)

Logistic Scores [0.92153589 0.94156928 0.91652755] 
SVM Scores [0.96494157 0.97996661 0.96494157] 
RandomForest Scores [0.94156928 0.95492487 0.92654424]
